// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0f3_bBlUhqLyL-vcpSSOYPNNPiShQEAM',
    appId: '1:1067030644558:web:8e8d9ece636277abf6801f',
    messagingSenderId: '1067030644558',
    projectId: 'it-evaluation-app-x9d2',
    authDomain: 'it-evaluation-app-x9d2.firebaseapp.com',
    storageBucket: 'it-evaluation-app-x9d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjnl6OxDr8r1RRznKOpKJJADp3hwbGxg',
    appId: '1:1067030644558:android:f0b0f6d81340d076f6801f',
    messagingSenderId: '1067030644558',
    projectId: 'it-evaluation-app-x9d2',
    storageBucket: 'it-evaluation-app-x9d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfC1m5KKi2EBdKI4pUn9pyGD50rO2GMKE',
    appId: '1:1067030644558:ios:eac26c15c4283f52f6801f',
    messagingSenderId: '1067030644558',
    projectId: 'it-evaluation-app-x9d2',
    storageBucket: 'it-evaluation-app-x9d2.firebasestorage.app',
    iosBundleId: 'com.msags.itEvaluationApp',
  );
}
